languageCode = 'jp-ja'
title = 'ストーのブログ'
theme = 'anubis'
enableRobotsTXT = true
googleAnalytics = "G-DNLGK3TWCX"
defaultContentLanguage = 'ja'

[params]
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto-without-switcher"
disableSummary = true

[[params.social]]
  id = "github"
  name = "ks1019"
[[params.social]]
  id = "twitter"
  name = "kotarong1"
[[params.social]]
  id = "linkedin"
  name = "kotarosuto"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:day/:title/"

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[languages]
  [languages.ja]
    languageCode = 'ja'
  [languages.en]
    languageCode = 'en'
    title = 'My Blog'
    weight = 2