languageCode = 'ja'
title = 'ストーのブログ'
theme = 'PaperMod'
enableRobotsTXT = true
defaultContentLanguage = 'ja'
paginate = 100

[params]
DateFormat = "2006-01-02"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/ks1019"
[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/kotarong1"
[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/kotarosuto"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:day/:slug/"

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[services]
  [services.googleAnalytics]
    id = "G-DNLGK3TWCX"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.x]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[languages]
  [languages.ja]
    languageCode = 'ja'
  [languages.en]
    languageCode = 'en'
    title = 'My Blog'
    weight = 2

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "keywords"
    weight = 80
  
  [[related.indices]]
    name = "date"
    weight = 40
